# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fernando Gómez Personal Site
email: gomezhyuuga@gmail.com
description: >
  Web developer, consultant and machine learning enthusiast located at CDMX.
  – A showcase of all of my work and my thoughts shared as blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
author: gomezhyuuga
url: "https://gomezhyuuga.github.io"
logo: /assets/img/logo.png
social:
  name: Fernando Gómez (gomezhyuuga)
  links:
    - https://www.linkedin.com/in/gomezhyuuga
    - https://gomezhyuuga.github.io/
    - https://github.com/gomezhyuuga/
    - https://twitter.com/GomezHyuuga
google_site_verification: of4E401vbz3ezePeFLElA42mgox1vAH9PBoA4YbT1X8
resume: "assets/box/resume.pdf"
user_linkedin: gomezhyuuga
user_twitter: GomezHyuuga
user_github:  gomezhyuuga

encoding: utf-8

# Permalinks
permalink: /:year/:month/:day/:title

collections:
  notebooks:
    output: true
    layout: post

# Build settings
markdown: kramdown
# kramdown:
#   math_engine: sskatex
#   math_engine_opts:
#     katex_js: '/katex/katex.min.js'

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-jupyter-notebook
  - jekyll-seo-tag


# gist:
#   noscript: false


google_analytics: UA-7199274-8

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/